# Generated by Django 3.0.7 on 2020-07-31 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200730_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='medical_data',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.MedicalData'),
        ),
    ]
