# Generated by Django 3.0.7 on 2020-09-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200731_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='school',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
