# Generated by Django 3.1.2 on 2020-10-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200903_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
