# Generated by Django 3.0.7 on 2020-06-19 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200619_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='born_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 1, 0), null=True),
        ),
        migrations.AlterField(
            model_name='yearsubscription',
            name='born_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 1, 0), null=True),
        ),
    ]
