# Generated by Django 3.1.2 on 2020-10-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_documenttype_staff_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='max_instances',
            field=models.IntegerField(default=0),
        ),
    ]
