# Generated by Django 3.0.7 on 2020-06-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200619_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearsubscription',
            name='group',
        ),
        migrations.RemoveField(
            model_name='yearsubscription',
            name='school',
        ),
        migrations.AlterField(
            model_name='yearsubscription',
            name='year',
            field=models.CharField(default='', max_length=250),
        ),
    ]
