# Generated by Django 3.0.7 on 2020-06-19 13:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0007_auto_20200619_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=240)),
                ('value', models.CharField(db_index=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(default='', max_length=250)),
                ('via', models.CharField(default='', max_length=250)),
                ('cap', models.CharField(default='', max_length=250)),
                ('country', models.CharField(default='', max_length=250)),
                ('nationality', models.CharField(default='', max_length=250)),
                ('born_date', models.DateField(default=datetime.datetime(1970, 1, 1, 1, 0), null=True)),
                ('home_phone', models.CharField(default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='compilation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='YearSubscription',
        ),
        migrations.AddField(
            model_name='keyval',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='personal_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='client.PersonalData'),
        ),
    ]
