# Generated by Django 3.0.7 on 2020-06-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('client', '0008_auto_20200619_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_private', models.BooleanField(default=False)),
                ('personal_data', models.BooleanField(default=False)),
                ('medical_data', models.BooleanField(default=False)),
                ('custom_data', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=250)),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='client.DocumentType'),
        ),
    ]
