# Generated by Django 3.1.4 on 2021-07-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_groupsettings'),
        ('client', '0008_usercode_avs_number'),
    ]

    operations = [
    ]
