# Generated by Django 3.1.4 on 2022-01-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_merge_20210723_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='midata_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercode',
            name='midata_token',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
