# Generated by Django 3.1.4 on 2022-01-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20220102_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='midata_code',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
