# Generated by Django 3.1.4 on 2022-01-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_usercode_midata_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercode',
            name='midata_code',
        ),
    ]
