# Generated by Django 3.0.7 on 2020-06-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('client', '0011_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
