# Generated by Django 3.0.7 on 2020-06-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_document_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='personal_data',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.PersonalData'),
        ),
    ]
