# Generated by Django 3.1.4 on 2022-01-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_remove_usercode_midata_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='key_extra',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
