# Generated by Django 3.1.4 on 2022-01-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_keys_key_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='custom_message_text',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='keys',
            name='key',
            field=models.CharField(db_index=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='keys',
            name='key_extra',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='keyval',
            name='key',
            field=models.CharField(db_index=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='keyval',
            name='value',
            field=models.CharField(db_index=True, max_length=2048),
        ),
    ]
