# Generated by Django 3.0.7 on 2020-06-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20200620_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='custom_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='custom_message_text',
            field=models.CharField(default='', max_length=250),
        ),
    ]
