# Generated by Django 3.0.7 on 2020-06-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20200620_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
    ]
