# Generated by Django 3.2.9 on 2022-09-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client', '0014_auto_20220111_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='HideGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.documenttype')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
