# Generated by Django 4.1.5 on 2023-07-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client', '0015_hidegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='branca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AddField(
            model_name='usercode',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='usercode',
            name='first_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='usercode',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
