# Generated by Django 4.1.5 on 2023-07-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_usercode_branca_usercode_email_usercode_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='usercode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.usercode'),
        ),
    ]
