# Generated by Django 3.0.7 on 2020-06-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20200620_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='medic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='client.MedicalData'),
        ),
    ]
