# Generated by Django 3.0.7 on 2020-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_usercode_medic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='medic_name',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
