# Generated by Django 4.1.5 on 2023-07-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_usercode_branca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='usercode',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.usercode'),
        ),
    ]
