# Generated by Django 3.0.7 on 2020-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20200620_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='medic_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
