# Generated by Django 3.0.7 on 2020-06-20 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20200620_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldata',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='allergy',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='cell_phone',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='drugs',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='drugs_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='emer_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='emer_phone',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='emer_relative',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='health_care',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='injuries',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='medic_address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='medic_phone',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='misc',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='misc_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='rc',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='rega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='sickness',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='tetanus_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 1, 0), null=True),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='vaccine',
            field=models.CharField(default='', max_length=250),
        ),
    ]
