# Generated by Django 3.0.7 on 2020-06-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_auto_20200620_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='sign_req',
            field=models.BooleanField(default=False),
        ),
    ]
