# Generated by Django 3.0.7 on 2020-06-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_documenttype_sign_req'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='sign_req',
            new_name='auto_sign',
        ),
    ]
