# Generated by Django 3.0.7 on 2020-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_auto_20200620_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldata',
            name='health_care_certificate',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='vac_certificate',
            field=models.FileField(default=None, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
