# Generated by Django 3.0.7 on 2020-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_auto_20200622_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='custom_group',
            field=models.BooleanField(default=False),
        ),
    ]
