# Generated by Django 3.0.7 on 2020-07-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_documenttype_custom_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signed_doc',
            field=models.FileField(default=None, null=True, upload_to='documents/'),
        ),
    ]
